export const MAX_CHAT_HISTORY_RUNS = 500;
export const MAX_CHAT_HISTORY_ARTIFACTS = 1_000;
export const MAX_CHAT_HISTORY_EVENTS = 2_000;
export const MAX_CHAT_HISTORY_TEXT_CHARACTERS = 16 * 1024 * 1024;
export const MAX_CHAT_HISTORY_TELEMETRY_CHARACTERS = 4 * 1024 * 1024;
export const MAX_CHAT_HISTORY_EVENT_DATA_CHARACTERS = 64 * 1024;
export const MAX_CHAT_HISTORY_FIELD_CHARACTERS = 1_000;
export const MAX_CHAT_HISTORY_ID_CHARACTERS = 128;
export const MAX_CHAT_HISTORY_TIMESTAMP_CHARACTERS = 64;

export const CHAT_HISTORY_TRUNCATED_EVENT_DATA =
  '{"_takos_history":"event_data_truncated"}';
