export const MAX_CLIENT_THREAD_TITLE_CHARACTERS = 240;
export const MAX_CHAT_THREAD_ID_CHARACTERS = 128;
export const MAX_CHAT_THREAD_SUMMARY_CHARACTERS = 2_000;
export const MAX_CHAT_THREAD_KEY_POINTS_CHARACTERS = 4_096;
export const MAX_CHAT_THREAD_KEY_POINTS = 12;
export const MAX_CHAT_THREAD_KEY_POINT_CHARACTERS = 160;
export const MAX_CHAT_THREAD_TIMESTAMP_CHARACTERS = 64;
export const MAX_CHAT_THREADS_PER_RESPONSE = 100;
