import { test } from "bun:test";
import { assertEquals } from "@takos/test/assert";

import { createApiRouter } from "../../worker/server/routes/api.ts";
import { TAKOS_API_ROUTE_INVENTORY } from "./route-inventory.ts";

// The checked-in inventory is generated by
// scripts/generate-route-inventory.mjs from the composed apiRouter. A route
// added, renamed, or removed without regenerating it fails here, and
// docs.takos.jp is gated against the same list (takos-control docs-shape R2).
test("route inventory matches the composed apiRouter", () => {
  const noop = async (_c: unknown, next: () => Promise<void>) => {
    await next();
  };
  const router = createApiRouter({
    requireAuth: noop as never,
    optionalAuth: noop as never,
  });
  const served = [
    ...new Set(
      router.routes
        .map((route: { path: string }) => route.path)
        .filter((path: string) => path !== "*" && !path.endsWith("*")),
    ),
  ]
    .map((path) => "/api" + path)
    .sort();

  assertEquals(TAKOS_API_ROUTE_INVENTORY, served);
});
