/**
 * Polls the local-substrate kernel for applied deployments and mirrors each
 * deployment's `desired.routes[]` into the Caddy admin API as reverse_proxy
 * route entries on `srv0`. Lets the dynamic `<assigned>.app.takos.test`
 * subdomains generated by manifests reach their backing service without
 * editing Caddyfile by hand.
 *
 * On every poll cycle, the registrar fetches the full applied-deployments
 * list from the kernel, materializes the routes, then PATCHes the entire
 * Caddy `srv0.routes` array as one transactional update. Idempotent on
 * restart: the first cycle replaces whatever was there with the kernel's
 * current truth.
 *
 * Phase 3 deliverable. Built as a small standalone Deno service so we
 * never have to touch upstream takosumi connectors.
 */

const KERNEL_URL = Deno.env.get("KERNEL_URL") ?? "http://kernel:8788";
const KERNEL_TOKEN = Deno.env.get("KERNEL_DEPLOY_TOKEN") ??
  Deno.env.get("TAKOSUMI_DEPLOY_TOKEN") ?? "";
const CADDY_ADMIN_URL = Deno.env.get("CADDY_ADMIN_URL") ??
  "http://caddy:2019";
const POLL_INTERVAL_MS = Number(Deno.env.get("POLL_INTERVAL_MS") ?? "5000");

interface KernelDeploymentRoute {
  readonly host?: string;
  readonly upstream?: string;
  readonly upstreamPort?: number;
}

interface KernelDeployment {
  readonly id: string;
  readonly status: string;
  readonly desired?: { readonly routes?: readonly KernelDeploymentRoute[] };
}

interface CaddyRoute {
  readonly match: readonly { readonly host: readonly string[] }[];
  readonly handle: readonly {
    readonly handler: "reverse_proxy";
    readonly upstreams: readonly { readonly dial: string }[];
  }[];
  readonly terminal: true;
}

async function fetchAppliedDeployments(): Promise<readonly KernelDeployment[]> {
  const res = await fetch(`${KERNEL_URL}/v1/deployments`, {
    headers: KERNEL_TOKEN ? { authorization: `Bearer ${KERNEL_TOKEN}` } : {},
  });
  if (!res.ok) {
    console.warn(
      `[route-registrar] kernel returned ${res.status} for /v1/deployments; skipping cycle`,
    );
    return [];
  }
  const body = await res.json() as
    | { readonly deployments?: readonly KernelDeployment[] }
    | readonly KernelDeployment[];
  if (Array.isArray(body)) return body;
  return body.deployments ?? [];
}

function caddyRouteFor(route: KernelDeploymentRoute): CaddyRoute | null {
  if (!route.host || !route.upstream) return null;
  const port = route.upstreamPort ?? 80;
  return {
    match: [{ host: [route.host] }],
    handle: [{
      handler: "reverse_proxy",
      upstreams: [{ dial: `${route.upstream}:${port}` }],
    }],
    terminal: true,
  };
}

async function syncCaddyRoutes(
  deployments: readonly KernelDeployment[],
): Promise<void> {
  const dynamicRoutes: CaddyRoute[] = [];
  for (const dep of deployments) {
    if (dep.status !== "applied") continue;
    for (const route of dep.desired?.routes ?? []) {
      const caddyRoute = caddyRouteFor(route);
      if (caddyRoute) dynamicRoutes.push(caddyRoute);
    }
  }
  // Replace ONLY the dynamic-route slot. Static routes (accounts, kernel,
  // app, git) are owned by Caddyfile and live on srv0 separately. We
  // namespace dynamic routes under @id "local-substrate-dynamic" via the
  // adapt API.
  const url =
    `${CADDY_ADMIN_URL}/id/local-substrate-dynamic/handle/0/routes`;
  const res = await fetch(url, {
    method: "PATCH",
    headers: { "content-type": "application/json" },
    body: JSON.stringify(dynamicRoutes),
  });
  if (!res.ok) {
    const text = await res.text();
    console.warn(
      `[route-registrar] Caddy admin PATCH returned ${res.status}: ${text}`,
    );
    return;
  }
  console.log(
    `[route-registrar] synced ${dynamicRoutes.length} dynamic route(s)`,
  );
}

async function tick(): Promise<void> {
  try {
    const deployments = await fetchAppliedDeployments();
    await syncCaddyRoutes(deployments);
  } catch (error) {
    console.warn(`[route-registrar] tick error: ${(error as Error).message}`);
  }
}

console.log(
  `[route-registrar] watching ${KERNEL_URL} -> ${CADDY_ADMIN_URL} every ${POLL_INTERVAL_MS}ms`,
);

await tick();
setInterval(tick, POLL_INTERVAL_MS);
