import type { D1Database } from '../../../shared/types/bindings.ts';
import type { Resource, ResourcePermission, ResourceType, ResourceStatus } from '../../../shared/types';
export declare function listResourcesForWorkspace(db: D1Database, userId: string, spaceId: string): Promise<{
    access_level: string;
    id: string;
    owner_id: string;
    space_id: string | null;
    name: string;
    type: ResourceType;
    status: ResourceStatus;
    cf_id: string | null;
    cf_name: string | null;
    config: string;
    metadata: string;
    size_bytes?: number;
    item_count?: number;
    last_used_at?: string | null;
    created_at: string;
    updated_at: string;
}[]>;
export declare function listResourcesForUser(db: D1Database, userId: string): Promise<{
    owned: {
        access_level: string;
        id: string;
        owner_id: string;
        space_id: string | null;
        name: string;
        type: ResourceType;
        status: ResourceStatus;
        cf_id: string | null;
        cf_name: string | null;
        config: string;
        metadata: string;
        size_bytes?: number;
        item_count?: number;
        last_used_at?: string | null;
        created_at: string;
        updated_at: string;
    }[];
    shared: {
        access_level: string;
        id: string;
        owner_id: string;
        space_id: string | null;
        name: string;
        type: ResourceType;
        status: ResourceStatus;
        cf_id: string | null;
        cf_name: string | null;
        config: string;
        metadata: string;
        size_bytes?: number;
        item_count?: number;
        last_used_at?: string | null;
        created_at: string;
        updated_at: string;
    }[];
}>;
export declare function listResourcesByType(db: D1Database, userId: string, resourceType: ResourceType): Promise<{
    access_level: string;
    id: string;
    owner_id: string;
    space_id: string | null;
    name: string;
    type: ResourceType;
    status: ResourceStatus;
    cf_id: string | null;
    cf_name: string | null;
    config: string;
    metadata: string;
    size_bytes?: number;
    item_count?: number;
    last_used_at?: string | null;
    created_at: string;
    updated_at: string;
}[]>;
export declare function getResourceById(db: D1Database, resourceId: string): Promise<Resource | null>;
export declare function getResourceByName(db: D1Database, userId: string, resourceName: string): Promise<{
    _internal_id: string;
    id: string;
    owner_id: string;
    space_id: string | null;
    name: string;
    type: ResourceType;
    status: ResourceStatus;
    cf_id: string | null;
    cf_name: string | null;
    config: string;
    metadata: string;
    size_bytes?: number;
    item_count?: number;
    last_used_at?: string | null;
    created_at: string;
    updated_at: string;
} | null>;
export declare function insertResource(db: D1Database, input: {
    id: string;
    owner_id: string;
    name: string;
    type: ResourceType;
    status: ResourceStatus;
    cf_id: string | null;
    cf_name: string;
    config: Record<string, unknown>;
    space_id?: string | null;
    created_at: string;
    updated_at: string;
}): Promise<Resource | null>;
export declare function insertFailedResource(db: D1Database, input: {
    id: string;
    owner_id: string;
    name: string;
    type: ResourceType;
    cf_name: string;
    config: Record<string, unknown>;
    space_id?: string | null;
    created_at: string;
    updated_at: string;
}): Promise<void>;
export declare function updateResourceMetadata(db: D1Database, resourceId: string, updates: {
    name?: string;
    config?: Record<string, unknown>;
    metadata?: Record<string, unknown>;
}): Promise<Resource | null>;
export declare function markResourceDeleting(db: D1Database, resourceId: string): Promise<void>;
export declare function deleteResource(db: D1Database, resourceId: string): Promise<void>;
export declare function getAvailableResourcesForWorkspace(db: D1Database, spaceId: string, resourceType: ResourceType): Promise<Array<Resource & {
    access_level: 'owner' | ResourcePermission;
}>>;
//# sourceMappingURL=store.d.ts.map