version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "04:15"
      timezone: "Etc/UTC"
    labels:
      - "dependencies"
      - "ci"
      - "security"
    open-pull-requests-limit: 5

  - package-ecosystem: "docker"
    directory: "/deploy/docker"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "04:25"
      timezone: "Etc/UTC"
    labels:
      - "dependencies"
      - "containers"
      - "security"
    open-pull-requests-limit: 5

  - package-ecosystem: "docker"
    directory: "/containers/agent"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "04:45"
      timezone: "Etc/UTC"
    labels:
      - "dependencies"
      - "containers"
      - "security"
    open-pull-requests-limit: 5

  - package-ecosystem: "cargo"
    directory: "/containers/agent"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "04:55"
      timezone: "Etc/UTC"
    labels:
      - "dependencies"
      - "rust"
      - "security"
    open-pull-requests-limit: 5
