export const MAX_CUSTOM_SKILL_REFERENCE_CHARACTERS = 128;
export const MAX_CUSTOM_SKILL_NAME_CHARACTERS = 200;
export const MAX_CUSTOM_SKILL_DESCRIPTION_CHARACTERS = 2_000;
export const MAX_CUSTOM_SKILL_INSTRUCTION_BYTES = 4 * 1_024;
export const MAX_CUSTOM_SKILL_TRIGGERS = 20;
export const MAX_CUSTOM_SKILL_TRIGGER_CHARACTERS = 100;
export const MAX_CUSTOM_SKILL_METADATA_LIST_ITEMS = 20;
export const MAX_CUSTOM_SKILL_RESOURCES = 8;
export const MAX_CUSTOM_SKILL_METADATA_ITEM_CHARACTERS = 128;
export const MAX_CUSTOM_SKILL_LIST_INPUT_CHARACTERS =
  MAX_CUSTOM_SKILL_METADATA_LIST_ITEMS *
  (MAX_CUSTOM_SKILL_METADATA_ITEM_CHARACTERS + 2);
