# Generated by scripts/generate-runtime-secret-names.ts from
# src/worker/shared/config/runtime-secrets.ts. Do not edit.

locals {
  runtime_secret_binding_names = [
    "ENCRYPTION_KEY",
    "PLATFORM_PRIVATE_KEY",
    "PLATFORM_PUBLIC_KEY",
    "TAKOS_AGENT_START_TOKEN",
    "TAKOS_INTERNAL_API_SECRET",
  ]
}
