/**
 * Host-side RPC handlers for tenant worker bindings that cannot be natively
 * provided by Miniflare (Vectorize, AI, Analytics Engine, Workflow).
 *
 * Each handler is registered as a Miniflare `serviceBinding` and receives
 * HTTP requests from the worker-side polyfill objects generated by
 * {@link ./tenant-binding-polyfills.ts}.
 *
 * RPC protocol: POST with JSON body to `/methodName`, JSON response.
 */
interface VectorizeAdapter {
    query(vector: number[], options?: Record<string, unknown>): Promise<unknown>;
    upsert(vectors: Array<{
        id: string;
        values: number[];
        namespace?: string;
        metadata?: Record<string, unknown>;
    }>): Promise<unknown>;
    deleteByIds(ids: string[]): Promise<unknown>;
    getByIds(ids: string[]): Promise<unknown>;
    describe(): Promise<unknown>;
}
interface AiAdapter {
    run(model: string, inputs: {
        text: string[];
    }): Promise<unknown>;
}
interface AnalyticsEngineAdapter {
    writeDataPoint(event: {
        blobs?: string[];
        doubles?: number[];
        indexes?: string[];
    }): void;
}
interface WorkflowAdapter {
    create(options?: {
        id?: string;
        params?: unknown;
    }): Promise<{
        id: string;
        pause(): Promise<void>;
        resume(): Promise<void>;
        terminate(): Promise<void>;
        restart(): Promise<void>;
        status(): Promise<unknown>;
    }>;
    get(id: string): Promise<{
        id: string;
        pause(): Promise<void>;
        resume(): Promise<void>;
        terminate(): Promise<void>;
        restart(): Promise<void>;
        status(): Promise<unknown>;
    }>;
}
export declare function createVectorizeServiceHandler(store: VectorizeAdapter): (request: Request) => Promise<Response>;
export declare function createAiServiceHandler(ai: AiAdapter): (request: Request) => Promise<Response>;
export declare function createAnalyticsServiceHandler(analytics: AnalyticsEngineAdapter): (request: Request) => Promise<Response>;
export declare function createWorkflowServiceHandler(workflow: WorkflowAdapter): (request: Request) => Promise<Response>;
export {};
//# sourceMappingURL=tenant-binding-rpc.d.ts.map