/**
 * Host-side RPC handlers for tenant worker bindings that cannot be natively
 * provided by Miniflare (Vectorize, AI, Analytics Engine, Workflow).
 *
 * Each handler is registered as a Miniflare `serviceBinding` and receives
 * HTTP requests from the worker-side polyfill objects generated by
 * {@link ./tenant-binding-polyfills.ts}.
 *
 * RPC protocol: POST with JSON body to `/methodName`, JSON response.
 */

// ---------------------------------------------------------------------------
// Types — minimal interfaces matching the adapters
// ---------------------------------------------------------------------------

interface VectorizeAdapter {
  query(vector: number[], options?: Record<string, unknown>): Promise<unknown>;
  upsert(vectors: Array<{ id: string; values: number[]; namespace?: string; metadata?: Record<string, unknown> }>): Promise<unknown>;
  deleteByIds(ids: string[]): Promise<unknown>;
  getByIds(ids: string[]): Promise<unknown>;
  describe(): Promise<unknown>;
}

interface AiAdapter {
  run(model: string, inputs: { text: string[] }): Promise<unknown>;
}

interface AnalyticsEngineAdapter {
  writeDataPoint(event: { blobs?: string[]; doubles?: number[]; indexes?: string[] }): void;
}

interface WorkflowAdapter {
  create(options?: { id?: string; params?: unknown }): Promise<{ id: string; pause(): Promise<void>; resume(): Promise<void>; terminate(): Promise<void>; restart(): Promise<void>; status(): Promise<unknown> }>;
  get(id: string): Promise<{ id: string; pause(): Promise<void>; resume(): Promise<void>; terminate(): Promise<void>; restart(): Promise<void>; status(): Promise<unknown> }>;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function jsonResponse(data: unknown, status = 200): Response {
  return new Response(JSON.stringify(data), {
    status,
    headers: { 'Content-Type': 'application/json' },
  });
}

function errorResponse(message: string, status = 400): Response {
  return jsonResponse({ error: message }, status);
}

async function parseBody<T = unknown>(request: Request): Promise<T> {
  return request.json() as Promise<T>;
}

function getMethod(request: Request): string {
  return new URL(request.url).pathname.replace(/^\//, '');
}

// ---------------------------------------------------------------------------
// Vectorize RPC Handler
// ---------------------------------------------------------------------------

export function createVectorizeServiceHandler(
  store: VectorizeAdapter,
): (request: Request) => Promise<Response> {
  return async (request: Request): Promise<Response> => {
    try {
      const method = getMethod(request);

      switch (method) {
        case 'query': {
          const { vector, options } = await parseBody<{ vector: number[]; options?: Record<string, unknown> }>(request);
          const result = await store.query(vector, options);
          return jsonResponse(result);
        }
        case 'upsert': {
          const { vectors } = await parseBody<{ vectors: Array<{ id: string; values: number[]; namespace?: string; metadata?: Record<string, unknown> }> }>(request);
          const result = await store.upsert(vectors);
          return jsonResponse(result);
        }
        case 'deleteByIds': {
          const { ids } = await parseBody<{ ids: string[] }>(request);
          const result = await store.deleteByIds(ids);
          return jsonResponse(result);
        }
        case 'getByIds': {
          const { ids } = await parseBody<{ ids: string[] }>(request);
          const result = await store.getByIds(ids);
          return jsonResponse(result);
        }
        case 'describe': {
          const result = await store.describe();
          return jsonResponse(result);
        }
        default:
          return errorResponse(`Unknown Vectorize method: ${method}`, 404);
      }
    } catch (error) {
      return errorResponse(error instanceof Error ? error.message : String(error), 500);
    }
  };
}

// ---------------------------------------------------------------------------
// AI RPC Handler
// ---------------------------------------------------------------------------

export function createAiServiceHandler(
  ai: AiAdapter,
): (request: Request) => Promise<Response> {
  return async (request: Request): Promise<Response> => {
    try {
      const method = getMethod(request);

      switch (method) {
        case 'run': {
          const { model, inputs } = await parseBody<{ model: string; inputs: { text: string[] } }>(request);
          const result = await ai.run(model, inputs);
          return jsonResponse(result);
        }
        default:
          return errorResponse(`Unknown AI method: ${method}`, 404);
      }
    } catch (error) {
      return errorResponse(error instanceof Error ? error.message : String(error), 500);
    }
  };
}

// ---------------------------------------------------------------------------
// Analytics Engine RPC Handler
// ---------------------------------------------------------------------------

export function createAnalyticsServiceHandler(
  analytics: AnalyticsEngineAdapter,
): (request: Request) => Promise<Response> {
  return async (request: Request): Promise<Response> => {
    try {
      const method = getMethod(request);

      switch (method) {
        case 'writeDataPoint': {
          const event = await parseBody<{ blobs?: string[]; doubles?: number[]; indexes?: string[] }>(request);
          analytics.writeDataPoint(event);
          return jsonResponse({ ok: true });
        }
        default:
          return errorResponse(`Unknown Analytics method: ${method}`, 404);
      }
    } catch (error) {
      return errorResponse(error instanceof Error ? error.message : String(error), 500);
    }
  };
}

// ---------------------------------------------------------------------------
// Workflow RPC Handler
// ---------------------------------------------------------------------------

export function createWorkflowServiceHandler(
  workflow: WorkflowAdapter,
): (request: Request) => Promise<Response> {
  return async (request: Request): Promise<Response> => {
    try {
      const method = getMethod(request);

      switch (method) {
        case 'create': {
          const options = await parseBody<{ id?: string; params?: unknown }>(request);
          const instance = await workflow.create(options);
          return jsonResponse({ id: instance.id });
        }
        case 'get': {
          const { id } = await parseBody<{ id: string }>(request);
          const instance = await workflow.get(id);
          return jsonResponse({ id: instance.id });
        }
        case 'status': {
          const { id } = await parseBody<{ id: string }>(request);
          const instance = await workflow.get(id);
          const result = await instance.status();
          return jsonResponse(result);
        }
        case 'pause': {
          const { id } = await parseBody<{ id: string }>(request);
          const instance = await workflow.get(id);
          await instance.pause();
          return jsonResponse({ ok: true });
        }
        case 'resume': {
          const { id } = await parseBody<{ id: string }>(request);
          const instance = await workflow.get(id);
          await instance.resume();
          return jsonResponse({ ok: true });
        }
        case 'terminate': {
          const { id } = await parseBody<{ id: string }>(request);
          const instance = await workflow.get(id);
          await instance.terminate();
          return jsonResponse({ ok: true });
        }
        case 'restart': {
          const { id } = await parseBody<{ id: string }>(request);
          const instance = await workflow.get(id);
          await instance.restart();
          return jsonResponse({ ok: true });
        }
        default:
          return errorResponse(`Unknown Workflow method: ${method}`, 404);
      }
    } catch (error) {
      return errorResponse(error instanceof Error ? error.message : String(error), 500);
    }
  };
}
