/**
 * Generates a wrapper entry script (`__takos_entry.mjs`) that intercepts
 * the tenant worker's env bindings and replaces CF-native bindings
 * (Vectorize, AI, Analytics Engine, Workflow) with polyfill objects that
 * delegate to host-side RPC service bindings.
 *
 * The generated script is pure ES module JavaScript — no TypeScript, no
 * external imports beyond the tenant's own `bundle.mjs`.
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type PolyfillBindingEntry = {
  /** Binding name as seen by tenant code (e.g., "VECTORIZE", "AI"). */
  name: string;
  /** Polyfill type determines which client object to generate. */
  type: "vectorize" | "ai" | "analytics_engine" | "workflow" | "queue";
  /** Name of the hidden Miniflare service binding for RPC. */
  rpcBindingName: string;
};

export type PolyfillConfig = {
  bindings: PolyfillBindingEntry[];
};

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Returns `null` if no polyfill bindings are needed (no wrapper necessary).
 */
export function generateWrapperScript(config: PolyfillConfig): string | null {
  if (config.bindings.length === 0) {
    return null;
  }

  const polyfillBlocks = config.bindings.map(generatePolyfillBlock);
  const envPatchLines = config.bindings.map(
    (b) =>
      `    env['${b.name}'] = __polyfill_${
        sanitize(b.name)
      }(env['${b.rpcBindingName}']);`,
  );

  return `// Auto-generated by takos — do not edit.
import worker from './bundle.mjs';

${polyfillBlocks.join("\n\n")}

function __patchEnv(env) {
${envPatchLines.join("\n")}
  return env;
}

export default {
  async fetch(request, env, ctx) {
    if (!worker.fetch) return new Response('Worker has no fetch handler', { status: 500 });
    return worker.fetch(request, __patchEnv(env), ctx);
  },
  async scheduled(controller, env, ctx) {
    if (!worker.scheduled) return;
    return worker.scheduled(controller, __patchEnv(env), ctx);
  },
  async queue(batch, env, ctx) {
    if (!worker.queue) return;
    return worker.queue(batch, __patchEnv(env), ctx);
  },
};
`;
}

// ---------------------------------------------------------------------------
// Per-binding polyfill generators
// ---------------------------------------------------------------------------

function generatePolyfillBlock(entry: PolyfillBindingEntry): string {
  const fnName = `__polyfill_${sanitize(entry.name)}`;

  switch (entry.type) {
    case "vectorize":
      return `function ${fnName}(rpc) {
  async function rpcCall(method, body) {
    const res = await rpc.fetch('http://rpc/' + method, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
    });
    if (!res.ok) {
      const err = await res.json().catch(() => ({ error: res.statusText }));
      throw new Error(err.error || 'Vectorize RPC error');
    }
    return res.json();
  }
  return {
    query(vector, options) { return rpcCall('query', { vector, options }); },
    upsert(vectors) { return rpcCall('upsert', { vectors }); },
    deleteByIds(ids) { return rpcCall('deleteByIds', { ids }); },
    getByIds(ids) { return rpcCall('getByIds', { ids }); },
    describe() { return rpcCall('describe', {}); },
  };
}`;

    case "ai":
      return `function ${fnName}(rpc) {
  return {
    async run(model, inputs, options) {
      const res = await rpc.fetch('http://rpc/run', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ model, inputs }),
      });
      if (!res.ok) {
        const err = await res.json().catch(() => ({ error: res.statusText }));
        throw new Error(err.error || 'AI RPC error');
      }
      return res.json();
    },
  };
}`;

    case "analytics_engine":
      return `function ${fnName}(rpc) {
  return {
    writeDataPoint(event) {
      // Fire-and-forget — matches CF's synchronous writeDataPoint() API.
      rpc.fetch('http://rpc/writeDataPoint', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(event),
      }).catch(() => { /* fire-and-forget: matches CF's synchronous writeDataPoint() API */ });
    },
  };
}`;

    case "workflow":
      return `function ${fnName}(rpc) {
  async function rpcCall(method, body) {
    const res = await rpc.fetch('http://rpc/' + method, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
    });
    if (!res.ok) {
      const err = await res.json().catch(() => ({ error: res.statusText }));
      throw new Error(err.error || 'Workflow RPC error');
    }
    return res.json();
  }
  function makeInstance(id) {
    return {
      id,
      pause() { return rpcCall('pause', { id }); },
      resume() { return rpcCall('resume', { id }); },
      terminate() { return rpcCall('terminate', { id }); },
      restart() { return rpcCall('restart', { id }); },
      status() { return rpcCall('status', { id }); },
    };
  }
  return {
    async create(options) {
      const result = await rpcCall('create', options || {});
      return makeInstance(result.id);
    },
    async get(id) {
      await rpcCall('get', { id });
      return makeInstance(id);
    },
  };
}`;

    case "queue":
      return `function ${fnName}(rpc) {
  async function rpcCall(method, body) {
    const res = await rpc.fetch('http://rpc/' + method, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
    });
    if (!res.ok) {
      const err = await res.json().catch(() => ({ error: res.statusText }));
      throw new Error(err.error || 'Queue RPC error');
    }
    return res.json();
  }
  return {
    async send(message, options) {
      await rpcCall('send', { message, options });
    },
    async sendBatch(messages) {
      await rpcCall('sendBatch', { messages: Array.from(messages || []) });
    },
  };
}`;
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function sanitize(name: string): string {
  return name.replace(/[^a-zA-Z0-9_]/g, "_");
}
