// Generated by scripts/generate-website-release-ref.ts. Do not edit.
//
// The install ref the website publishes is the package version, so the deep
// link, the self-host runbook and the release tag cannot disagree.
export const TAKOS_INSTALL_REF = "v0.12.7";
