export {
  DEFAULT_CHAT_TIMELINE_MESSAGES,
  MAX_CHAT_TIMELINE_MESSAGES,
  MAX_CLIENT_ATTACHMENT_ID_CHARACTERS,
  MAX_CLIENT_ATTACHMENT_MIME_CHARACTERS,
  MAX_CLIENT_ATTACHMENT_NAME_CHARACTERS,
  MAX_CLIENT_ATTACHMENT_PATH_CHARACTERS,
  MAX_CLIENT_ATTACHMENT_SIZE_BYTES,
  MAX_CLIENT_MESSAGE_ATTACHMENTS,
  MAX_CLIENT_MESSAGE_CHARACTERS,
} from "../../../contracts/public/chat-message.ts";
