// Static 1st-party fallback catalog for the default-app distribution
// (see takos/./default-app-distribution.ts).
//
// This is the hardcoded list of `takos-{docs,excel,slide,computer}`, `yurucommu`,
// and `road-to-me` entries that ship as `InstallableApp`s with Takos and that
// auto-install into new spaces when no operator-supplied distribution is
// configured. Each entry's `repositoryEnvKey` maps to an env var operators can
// set to override the per-app repository URL without replacing the whole
// distribution.
export const FALLBACK_DEFAULT_APP_DISTRIBUTION = [
  {
    name: "takos-docs",
    title: "Docs",
    appId: "jp.takos.docs",
    description: "Rich text document editor with a Streamable HTTP MCP server.",
    publisher: "takos",
    homepage: "https://github.com/tako0614/takos-docs",
    icon: "/icons/docs.svg",
    category: "app",
    tags: ["default-app", "takos", "docs", "office"],
    repositoryUrl: "https://github.com/tako0614/takos-docs.git",
    repositoryEnvKey: "TAKOS_DEFAULT_DOCS_APP_REPOSITORY_URL",
    ref: "v0.1.2",
    refType: "tag",
    entryManifest: ".takosumi.yml",
    runtimeModes: ["shared-cell", "dedicated", "self-hosted"],
    bindings: [
      { name: "auth", type: "identity.oidc@v1", required: true },
      {
        name: "documents",
        type: "object-store.s3-compatible@v1",
        required: true,
      },
      { name: "domain", type: "domain.http@v1", required: false },
      { name: "bootstrap", type: "install-launch-token@v1", required: true },
    ],
  },
  {
    name: "takos-excel",
    title: "Excel",
    appId: "jp.takos.excel",
    description:
      "Spreadsheet editor with formulas and a Streamable HTTP MCP server.",
    publisher: "takos",
    homepage: "https://github.com/tako0614/takos-excel",
    icon: "/icons/excel.svg",
    category: "app",
    tags: ["default-app", "takos", "excel", "office", "spreadsheet"],
    repositoryUrl: "https://github.com/tako0614/takos-excel.git",
    repositoryEnvKey: "TAKOS_DEFAULT_EXCEL_APP_REPOSITORY_URL",
    ref: "v0.1.2",
    refType: "tag",
    entryManifest: ".takosumi.yml",
    runtimeModes: ["shared-cell", "dedicated", "self-hosted"],
    bindings: [
      { name: "auth", type: "identity.oidc@v1", required: true },
      {
        name: "spreadsheets",
        type: "object-store.s3-compatible@v1",
        required: true,
      },
      { name: "domain", type: "domain.http@v1", required: false },
      { name: "bootstrap", type: "install-launch-token@v1", required: true },
    ],
  },
  {
    name: "takos-slide",
    title: "Slide",
    appId: "jp.takos.slide",
    description: "Presentation editor with a Streamable HTTP MCP server.",
    publisher: "takos",
    homepage: "https://github.com/tako0614/takos-slide",
    icon: "/icons/slide.svg",
    category: "app",
    tags: ["default-app", "takos", "slide", "office", "presentation"],
    repositoryUrl: "https://github.com/tako0614/takos-slide.git",
    repositoryEnvKey: "TAKOS_DEFAULT_SLIDE_APP_REPOSITORY_URL",
    ref: "v0.1.2",
    refType: "tag",
    entryManifest: ".takosumi.yml",
    runtimeModes: ["shared-cell", "dedicated", "self-hosted"],
    bindings: [
      { name: "auth", type: "identity.oidc@v1", required: true },
      {
        name: "presentations",
        type: "object-store.s3-compatible@v1",
        required: true,
      },
      { name: "domain", type: "domain.http@v1", required: false },
      { name: "bootstrap", type: "install-launch-token@v1", required: true },
    ],
  },
  {
    name: "takos-computer",
    title: "Computer",
    appId: "jp.takos.computer",
    description:
      "Browser automation and sandbox computer with a Streamable HTTP MCP server.",
    publisher: "takos",
    homepage: "https://github.com/tako0614/takos-computer",
    icon: "/icons/computer.svg",
    category: "app",
    tags: ["default-app", "takos", "computer", "agent", "automation"],
    repositoryUrl: "https://github.com/tako0614/takos-computer.git",
    repositoryEnvKey: "TAKOS_DEFAULT_COMPUTER_APP_REPOSITORY_URL",
    ref: "v2.1.2",
    refType: "tag",
    entryManifest: ".takosumi.yml",
    runtimeModes: ["shared-cell", "dedicated", "self-hosted"],
    bindings: [
      { name: "auth", type: "identity.oidc@v1", required: true },
      { name: "domain", type: "domain.http@v1", required: false },
      { name: "bootstrap", type: "install-launch-token@v1", required: true },
    ],
  },
  {
    name: "yurucommu",
    title: "Yurucommu",
    appId: "com.yurucommu.app",
    description:
      "Self-hosted ActivityPub community social app for small communities.",
    publisher: "takos",
    homepage: "https://github.com/tako0614/yurucommu",
    icon: undefined,
    category: "social",
    tags: ["default-app", "takos", "yurucommu", "social", "activitypub"],
    repositoryUrl: "https://github.com/tako0614/yurucommu.git",
    repositoryEnvKey: "TAKOS_DEFAULT_YURUCOMMU_APP_REPOSITORY_URL",
    ref: "v1.2.6",
    refType: "tag",
    entryManifest: ".takosumi.yml",
    runtimeModes: ["shared-cell", "dedicated", "self-hosted"],
    bindings: [
      { name: "auth", type: "identity.oidc@v1", required: true },
      { name: "db", type: "database.postgres@v1", required: true },
      {
        name: "media",
        type: "object-store.s3-compatible@v1",
        required: true,
      },
      { name: "domain", type: "domain.http@v1", required: true },
      { name: "bootstrap", type: "install-launch-token@v1", required: true },
    ],
  },
  {
    name: "road-to-me",
    title: "Road to Me",
    appId: "jp.takos.road-to-me",
    description: "AI goal planning app for reverse timeline planning.",
    publisher: "takos",
    homepage: "https://github.com/tako0614/road-to-me",
    icon: undefined,
    category: "app",
    tags: ["takos", "road-to-me", "planning", "goals"],
    repositoryUrl: "https://github.com/tako0614/road-to-me.git",
    repositoryEnvKey: "TAKOS_DEFAULT_ROAD_TO_ME_APP_REPOSITORY_URL",
    ref: "v0.1.0",
    refType: "tag",
    entryManifest: ".takosumi.yml",
    runtimeModes: ["dedicated", "self-hosted"],
    bindings: [
      { name: "auth", type: "identity.oidc@v1", required: true },
      { name: "db", type: "database.postgres@v1", required: true },
      { name: "domain", type: "domain.http@v1", required: false },
      { name: "bootstrap", type: "install-launch-token@v1", required: true },
    ],
    preinstall: false,
  },
] as const;
