import type { WorkerBinding } from "../../../platform/backends/cloudflare/wfp.ts";
import type { AppCompute } from "../source/app-manifest-types.ts";
import {
  attachedWorkloadName,
  type ObservedGroupState,
  resolveWorkloadBaseUrl,
} from "./group-state.ts";

type AppWorker = AppCompute & { kind: "worker" };

export type AttachedContainerBindingPlan = {
  childName: string;
  workloadName: string;
  bindingName: string;
  urlEnvName: string;
  className: string;
  baseUrl: string;
};

function normalizeBindingSegment(value: string): string {
  const normalized = String(value || "")
    .trim()
    .replace(/[^A-Za-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .toUpperCase();
  return normalized || "CONTAINER";
}

function normalizeClassSegment(value: string): string {
  const normalized = String(value || "")
    .trim()
    .replace(/[^A-Za-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
  return normalized || "Container";
}

export function attachedContainerBindingName(childName: string): string {
  return `${normalizeBindingSegment(childName)}_CONTAINER`;
}

export function attachedContainerClassName(childName: string): string {
  return `__TakosAttachedContainer_${normalizeClassSegment(childName)}`;
}

export function attachedContainerUrlEnvName(childName: string): string {
  return `__TAKOS_ATTACHED_CONTAINER_${normalizeBindingSegment(childName)}_URL`;
}

export function resolveAttachedContainerBindingPlans(
  workerName: string,
  workerSpec: AppWorker,
  observedState: ObservedGroupState | null,
): AttachedContainerBindingPlan[] {
  const containers = workerSpec.containers ?? {};
  const plans: AttachedContainerBindingPlan[] = [];

  for (const childName of Object.keys(containers)) {
    const workloadName = attachedWorkloadName(workerName, childName);
    const observedWorkload = observedState?.workloads[workloadName];
    const baseUrl = resolveWorkloadBaseUrl(observedWorkload);
    if (!baseUrl) {
      throw new Error(
        `Attached container '${childName}' for worker '${workerName}' has no resolved endpoint; deploy '${workloadName}' first`,
      );
    }
    plans.push({
      childName,
      workloadName,
      bindingName: attachedContainerBindingName(childName),
      urlEnvName: attachedContainerUrlEnvName(childName),
      className: attachedContainerClassName(childName),
      baseUrl,
    });
  }

  return plans;
}

export function injectAttachedContainerBindings(input: {
  bundleContent: string;
  bindings: WorkerBinding[];
  plans: AttachedContainerBindingPlan[];
}): { bundleContent: string; bindings: WorkerBinding[] } {
  if (input.plans.length === 0) {
    return {
      bundleContent: input.bundleContent,
      bindings: input.bindings,
    };
  }

  const bindingNames = new Set(input.bindings.map((binding) => binding.name));
  for (const plan of input.plans) {
    if (bindingNames.has(plan.bindingName)) {
      throw new Error(
        `Attached container binding '${plan.bindingName}' conflicts with an existing worker binding`,
      );
    }
    if (bindingNames.has(plan.urlEnvName)) {
      throw new Error(
        `Attached container endpoint binding '${plan.urlEnvName}' conflicts with an existing worker binding`,
      );
    }
    bindingNames.add(plan.bindingName);
    bindingNames.add(plan.urlEnvName);
  }

  return {
    bundleContent: `${input.bundleContent}\n\n${
      generateAttachedContainerRuntime(input.plans)
    }\n`,
    bindings: [
      ...input.bindings,
      ...input.plans.flatMap((plan): WorkerBinding[] => [
        {
          type: "plain_text",
          name: plan.urlEnvName,
          text: plan.baseUrl,
        },
        {
          type: "durable_object_namespace",
          name: plan.bindingName,
          class_name: plan.className,
        },
      ]),
    ],
  };
}

function generateAttachedContainerRuntime(
  plans: AttachedContainerBindingPlan[],
): string {
  const classes = plans.map((plan) =>
    `export class ${plan.className} {
  constructor(_state, env) {
    this.env = env;
  }

  async fetch(request) {
    return __takosForwardAttachedContainer(request, this.env, ${
      JSON.stringify({
        bindingName: plan.bindingName,
        urlEnvName: plan.urlEnvName,
      })
    });
  }
}`
  ).join("\n\n");

  return `// Auto-generated by Takos attached container binding injection.
function __takosAttachedContainerRequest(request, baseUrl) {
  const original = new URL(request.url);
  const normalizedBase = String(baseUrl || "").replace(/\\/+$/, "") + "/";
  const target = new URL(original.pathname.replace(/^\\/+/, "") + original.search, normalizedBase);
  return new Request(target, request);
}

async function __takosForwardAttachedContainer(request, env, config) {
  const baseUrl = env[config.urlEnvName];
  if (!baseUrl) {
    return new Response(
      "Attached container endpoint is not configured: " + config.bindingName,
      { status: 503 },
    );
  }
  const forwarded = __takosAttachedContainerRequest(request, baseUrl);
  forwarded.headers.set("X-Takos-Attached-Container", config.bindingName);
  return fetch(forwarded);
}

${classes}`;
}
