#!/usr/bin/env bun

/**
 * Projects the Queue topology contract into the two places a deployment reads
 * it: the OpenTofu module's `queue_consumers` local, and `wrangler.toml`'s
 * production and staging consumer blocks.
 *
 * Before this, all three were hand-maintained and had drifted. `--check`
 * regenerates and diffs, so the drift cannot come back silently.
 */

import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

import {
  QUEUE_CONSUMERS,
  QUEUE_PRODUCERS,
  queueSuffix,
} from "./queue-consumer-contract.ts";

const root = resolve(import.meta.dir, "..");
const generatedTf =
  "deploy/opentofu/cloudflare/modules/platform/queue-consumers.generated.tf";
const wranglerPath = "deploy/cloudflare/wrangler.toml";
const BEGIN = "# BEGIN generated queue topology";
const END = "# END generated queue topology";
const NOTE =
  "# Generated by scripts/generate-queue-topology.ts from\n" +
  "# scripts/queue-consumer-contract.ts. Do not edit between the markers.";

function terraform(): string {
  const entries = QUEUE_CONSUMERS.map((consumer) =>
    [
      `    ${consumer.queueKey} = {`,
      `      queue_key        = ${JSON.stringify(consumer.queueKey)}`,
      `      dlq_key          = ${
        consumer.deadLetterQueueKey === null
          ? "null"
          : JSON.stringify(consumer.deadLetterQueueKey)
      }`,
      `      batch_size       = ${consumer.batchSize}`,
      `      max_wait_time_ms = ${consumer.batchTimeoutSeconds * 1000}`,
      `      max_retries      = ${consumer.maxRetries}`,
      `      max_concurrency  = ${consumer.maxConcurrency}`,
      `      retry_delay      = ${consumer.retryDelaySeconds}`,
      `    }`,
    ].join("\n")
  ).join("\n");
  return [
    "# Generated by scripts/generate-queue-topology.ts from",
    "# scripts/queue-consumer-contract.ts. Do not edit.",
    "",
    "locals {",
    "  queue_consumers = {",
    entries,
    "  }",
    "}",
    "",
  ].join("\n");
}

function wranglerConsumers(prefix: string, suffix: string): string {
  return QUEUE_CONSUMERS.map((consumer) => {
    const lines = [
      `[[${prefix}queues.consumers]]`,
      `queue = "takos-${consumer.suffix}${suffix}"`,
      `max_batch_size = ${consumer.batchSize}`,
      `max_batch_timeout = ${consumer.batchTimeoutSeconds}`,
      `max_retries = ${consumer.maxRetries}`,
      `max_concurrency = ${consumer.maxConcurrency}`,
      `retry_delay = ${consumer.retryDelaySeconds}`,
    ];
    if (consumer.deadLetterQueueKey !== null) {
      lines.push(
        `dead_letter_queue = "takos-${
          queueSuffix(consumer.deadLetterQueueKey)
        }${suffix}"`,
      );
    }
    return lines.join("\n");
  }).join("\n\n");
}

function wranglerProducers(prefix: string, suffix: string): string {
  return QUEUE_PRODUCERS.map((producer) =>
    [
      `[[${prefix}queues.producers]]`,
      `queue = "takos-${queueSuffix(producer.queueKey)}${suffix}"`,
      `binding = "${producer.binding}"`,
    ].join("\n")
  ).join("\n\n");
}

function block(prefix: string, environmentSuffix: string): string {
  return [
    BEGIN,
    NOTE,
    "",
    wranglerProducers(prefix, environmentSuffix),
    "",
    wranglerConsumers(prefix, environmentSuffix),
    "",
    END,
  ].join("\n");
}

function replaceBlock(source: string, replacement: string): string {
  const begin = source.indexOf(BEGIN);
  const end = source.indexOf(END, begin);
  if (begin === -1 || end === -1) {
    throw new Error(
      `${wranglerPath} is missing a ${BEGIN} / ${END} pair; the queue topology block cannot be projected`,
    );
  }
  return (
    source.slice(0, begin) + replacement + source.slice(end + END.length)
  );
}

function projectWrangler(source: string): string {
  let next = replaceBlock(source, block("", ""));
  const secondBegin = next.indexOf(BEGIN, next.indexOf(END) + END.length);
  if (secondBegin === -1) {
    throw new Error(
      `${wranglerPath} declares only one queue topology block; the staging environment needs its own`,
    );
  }
  const head = next.slice(0, secondBegin);
  const tail = next.slice(secondBegin);
  return head + replaceBlock(tail, block("env.staging.", "-staging"));
}

const wranglerSource = await readFile(resolve(root, wranglerPath), "utf8");
const nextWrangler = projectWrangler(wranglerSource);
const nextTerraform = terraform();
const currentTerraform = await readFile(resolve(root, generatedTf), "utf8")
  .catch(() => null);

const stale: string[] = [];
if (currentTerraform !== nextTerraform) stale.push(generatedTf);
if (wranglerSource !== nextWrangler) stale.push(wranglerPath);

if (Bun.argv.includes("--check")) {
  if (stale.length > 0) {
    console.error(
      `queue topology is stale in ${stale.join(", ")}; run bun run generate:queue-topology`,
    );
    process.exit(1);
  }
  console.log(
    `queue topology matches the contract in ${QUEUE_CONSUMERS.length} consumer(s)`,
  );
} else {
  if (currentTerraform !== nextTerraform) {
    await writeFile(resolve(root, generatedTf), nextTerraform);
  }
  if (wranglerSource !== nextWrangler) {
    await writeFile(resolve(root, wranglerPath), nextWrangler);
  }
  console.log(
    stale.length === 0
      ? "queue topology already matches the contract"
      : `queue topology written to ${stale.join(", ")}`,
  );
}
