#!/usr/bin/env -S bun

import { readFileSync } from "node:fs";
import path from "node:path";
import process from "node:process";

const repoRoot = path.resolve(import.meta.dir, "..");
const promptRoot = path.join(
  repoRoot,
  "src/worker/application/services/agent/prompts",
);
const outputPath = path.join(
  repoRoot,
  "src/worker/application/services/agent/prompt-assets.generated.ts",
);

const assets = [
  ["corePromptMarkdown", "core.md"],
  ["toolRuntimeRulesMarkdown", "tool-runtime-rules.md"],
  ["responseGuidelinesMarkdown", "response-guidelines.md"],
  ["generalWorkflowMarkdown", "general-workflow.md"],
  ["modeDefaultMarkdown", "modes/default.md"],
  ["modeResearcherMarkdown", "modes/researcher.md"],
  ["modeImplementerMarkdown", "modes/implementer.md"],
  ["modeReviewerMarkdown", "modes/reviewer.md"],
  ["modeAssistantMarkdown", "modes/assistant.md"],
  ["modePlannerMarkdown", "modes/planner.md"],
  ["researchBriefJaMarkdown", "skills/research-brief.ja.md"],
  ["researchBriefEnMarkdown", "skills/research-brief.en.md"],
  ["writingDraftJaMarkdown", "skills/writing-draft.ja.md"],
  ["writingDraftEnMarkdown", "skills/writing-draft.en.md"],
  ["planningStructurerJaMarkdown", "skills/planning-structurer.ja.md"],
  ["planningStructurerEnMarkdown", "skills/planning-structurer.en.md"],
  ["slidesAuthorJaMarkdown", "skills/slides-author.ja.md"],
  ["slidesAuthorEnMarkdown", "skills/slides-author.en.md"],
  ["repoAppOperatorJaMarkdown", "skills/repo-app-operator.ja.md"],
  ["repoAppOperatorEnMarkdown", "skills/repo-app-operator.en.md"],
] as const;

function renderPromptAssets(): string {
  const lines = [
    "// This file is generated by scripts/generate-agent-prompt-assets.ts.",
    "// Edit the Markdown files under ./prompts and regenerate; do not edit this file directly.",
    "",
  ];
  for (const [exportName, relativePath] of assets) {
    const markdown = readFileSync(path.join(promptRoot, relativePath), "utf8");
    lines.push(`export const ${exportName} =`);
    lines.push(`  ${JSON.stringify(markdown)};`);
  }
  return `${lines.join("\n")}\n`;
}

const expected = renderPromptAssets();
if (process.argv.includes("--check")) {
  const actual = readFileSync(outputPath, "utf8");
  if (actual !== expected) {
    console.error(
      "Agent prompt assets are stale. Run `bun run generate:agent-prompts`.",
    );
    process.exit(1);
  }
  console.log("Agent prompt assets are current.");
} else {
  await Bun.write(outputPath, expected);
  console.log(
    `Generated ${path.relative(repoRoot, outputPath)} from ${assets.length} Markdown assets.`,
  );
}
