#!/usr/bin/env bun

/**
 * Projects the runtime-secret name set into the two OpenTofu modules and
 * checks every operator-facing document that lists it.
 *
 * The set used to be retyped in nine places: four TypeScript files (now
 * importing `REQUIRED_RUNTIME_SECRET_NAMES` directly), the platform module's
 * `runtime_secret_binding_names` local, two reserved-binding-name validations,
 * a `.tftest.hcl` assertion, and four documents. A name added to the Worker's
 * contract had to be found in all of them by hand.
 */

import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

import { REQUIRED_RUNTIME_SECRET_NAMES } from "../src/worker/shared/config/runtime-secrets.ts";

const root = resolve(import.meta.dir, "..");
const names = [...REQUIRED_RUNTIME_SECRET_NAMES];

const generatedFiles = [
  "deploy/opentofu/cloudflare/runtime-secret-names.generated.tf",
  "deploy/opentofu/cloudflare/modules/platform/runtime-secret-names.generated.tf",
];

/** Documents that list the names for an operator. */
const documents = [
  "deploy/TAKOSUMI_DEPLOY.md",
  "docs/deploy/runtime-secrets.md",
  "docs/deploy/index.md",
  ".well-known/takosumi.json",
  "deploy/opentofu/cloudflare/opentofu.tfvars.example",
  "deploy/opentofu/cloudflare/variables.tf",
];

function generated(): string {
  return [
    "# Generated by scripts/generate-runtime-secret-names.ts from",
    "# src/worker/shared/config/runtime-secrets.ts. Do not edit.",
    "",
    "locals {",
    "  runtime_secret_binding_names = [",
    ...names.map((name) => `    ${JSON.stringify(name)},`),
    "  ]",
    "}",
    "",
  ].join("\n");
}

const wanted = generated();
const stale: string[] = [];
for (const path of generatedFiles) {
  const current = await readFile(resolve(root, path), "utf8").catch(() => null);
  if (current !== wanted) stale.push(path);
}

/** A document must name every secret, and must not present an extra one. */
const documentFailures: string[] = [];
for (const path of documents) {
  const text = await readFile(resolve(root, path), "utf8");
  const missing = names.filter((name) => !text.includes(name));
  if (missing.length > 0) {
    documentFailures.push(`${path}: does not name ${missing.join(", ")}`);
  }
  const countWord = names.length === 5 ? /\bfive\b|五つ|5 つ/u : null;
  if (countWord !== null && /runtime secret|runtime_secret|ランタイムシークレット/u.test(text) && !countWord.test(text)) {
    documentFailures.push(
      `${path}: describes the runtime secrets without stating that there are ${names.length}`,
    );
  }
}

if (Bun.argv.includes("--check")) {
  const failures = [
    ...stale.map((path) =>
      `${path} is stale; run bun run generate:runtime-secret-names`
    ),
    ...documentFailures,
  ];
  if (failures.length > 0) {
    console.error("runtime secret names are not projected:");
    for (const failure of failures) console.error(`- ${failure}`);
    process.exit(1);
  }
  console.log(
    `runtime secret names projected into ${generatedFiles.length} module(s) and named in ${documents.length} document(s)`,
  );
} else {
  for (const path of stale) await writeFile(resolve(root, path), wanted);
  if (documentFailures.length > 0) {
    console.error("documents still need editing by hand:");
    for (const failure of documentFailures) console.error(`- ${failure}`);
    process.exit(1);
  }
  console.log(
    stale.length === 0
      ? "runtime secret names already projected"
      : `runtime secret names written to ${stale.join(", ")}`,
  );
}
