#!/usr/bin/env bun

/**
 * Projects the Takos package version into the one module the website reads for
 * its install ref.
 *
 * The website used to carry the tag as a literal (`DEFAULT_TAKOS_REF`) that a
 * person advanced by hand. It sat at `v0.12.8` against a `package.json` at
 * `0.12.7` and a repository whose newest tag was `v0.12.7`: the next website
 * deploy would have shipped an install link and a self-host runbook naming a
 * ref that resolves nowhere. takos.jp is still serving `ref=v0.12.1`, so the
 * defect was armed rather than live.
 *
 * The version is the authority. Advancing the published ref is then exactly
 * one act — bumping the package version — and `takos-site` refuses to publish
 * while the tag it would name does not exist on `origin`.
 */

import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const root = resolve(import.meta.dir, "..");
const generatedPath = "website/src/lib/takos-release.generated.ts";

const packageJson = JSON.parse(
  await readFile(resolve(root, "package.json"), "utf8"),
) as { version: string; takosRelease?: { version?: string } };

if (packageJson.takosRelease?.version !== packageJson.version) {
  console.error(
    `package.json takosRelease.version (${packageJson.takosRelease?.version}) must equal version (${packageJson.version})`,
  );
  process.exit(1);
}

export const TAKOS_INSTALL_REF = `v${packageJson.version}`;

const generated = `// Generated by scripts/generate-website-release-ref.ts. Do not edit.
//
// The install ref the website publishes is the package version, so the deep
// link, the self-host runbook and the release tag cannot disagree.
export const TAKOS_INSTALL_REF = ${JSON.stringify(TAKOS_INSTALL_REF)};
`;

const target = resolve(root, generatedPath);
const current = await readFile(target, "utf8").catch(() => null);

// The operator-facing self-host snippet names the same tag in prose, so the
// relation is checked there too rather than left to go stale.
const readmePath = "website/README.md";
const readme = await readFile(resolve(root, readmePath), "utf8");
const readmeRef = readme.match(/^release=(\S+)$/mu)?.[1];

if (Bun.argv.includes("--check")) {
  if (current !== generated) {
    console.error(
      `${generatedPath} is stale; run bun run generate:website-release-ref`,
    );
    process.exit(1);
  }
  if (readmeRef !== TAKOS_INSTALL_REF) {
    console.error(
      `${readmePath} self-host snippet says release=${readmeRef}; the package version is ${TAKOS_INSTALL_REF}`,
    );
    process.exit(1);
  }
  console.log(`${generatedPath} matches package version ${TAKOS_INSTALL_REF}`);
} else if (readmeRef !== TAKOS_INSTALL_REF) {
  const rewritten = readme.replace(
    /^release=\S+$/mu,
    `release=${TAKOS_INSTALL_REF}`,
  );
  await writeFile(resolve(root, readmePath), rewritten);
  if (current !== generated) await writeFile(target, generated);
  console.log(
    `${generatedPath} and ${readmePath} written for ${TAKOS_INSTALL_REF}`,
  );
} else if (current === generated) {
  console.log(`${generatedPath} already matches ${TAKOS_INSTALL_REF}`);
} else {
  await writeFile(target, generated);
  console.log(`${generatedPath} written for ${TAKOS_INSTALL_REF}`);
}
